### PR TITLE
Reducing logging verbosity.

### PR DESCRIPTION
**Pull request by cschroed-usgs**
Reverts USGS-CIDA/sedmap#67

Sorry for all the reverts. I did not mean to merge the first one without review.

### CODE REVIEW

**Comment by duselmann** [comment]
Carl, I have found that one location logs an ERROR level entry for each line in the large downloads. This must by why we are not realizing any improvement when reducing the logging threshold. I have made changes in the area of code that causes this. Both fixed the reason it was logging and for now removed the line that is logging. This might not be the only issue, but I am convinced it is at least one of them.

**Comment by cschroed-usgs** [comment]
Sounds good! Should we close this without merging then?

**Comment by duselmann** [comment]
After much deliberation, I am choosing to merge this revision.

**Comment by cschroed-usgs** [comment]
:+1:

**Pull request merged**
